name: ccnn
channels:
  - pytorch
  - defaults
  - pyg
dependencies:
  - python=3.9
  - h5py
  - matplotlib
  - torchaudio
  - scikit-learn
  - pytorch
  - torchvision
  - torchtext
  - plotly
  - pyg
  - pip
  - pip:
    - hydra-core
    - wandb
    - datasets
    - pytorch-lightning
