from .mnist import MNISTDataModule
from .cifar10 import CIFAR10DataModule
from .speech_commands import SpeechCommandsDataModule
from .physionet import PhysioNetDataModule
from .qm9 import QM9DataModule
from .cifar100 import CIFAR100DataModule
from .stl10 import STL10DataModule
from .pathfinder import PathFinderDataModule
from .imdb import IMDBDataModule
from .listops import ListOpsDataModule
from .modelnet40 import ModelNet40DataModule
