from .mnist import MNISTDataModule
from .cifar10 import CIFAR10DataModule
from .speech_commands import SpeechCommandsDataModule
from .physionet import PhysioNetDataModule
from .cifar100 import CIFAR100DataModule
from .stl10 import STL10DataModule
from .pathfinder import PathFinderDataModule
from .imdb import IMDBDataModule
from .listops import ListOpsDataModule
